Handle GCE VM creation error  'Instance failed to start due to preemption.' before 'Could not fetch resource'. This is necessary because it is a suberror. Full error is:
```
perfkitbenchmarker.errors.Benchmarks.UnsupportedConfigError: ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - Instance failed to start due to preemption.
```

PiperOrigin-RevId: 434594304